# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [2]:
import pandas as pd
import numpy as np

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [14]:

arr = np.random.randint(1 , 27 , size=(6 , 4))
print("Array:")
print(arr)

df = pd.DataFrame(arr)
df.set_index(0 , inplace=True)
df

Array:
[[15  2 26 11]
 [19 24 22 17]
 [12 19 19  7]
 [ 7 21 19 13]
 [10  3 26  7]
 [16 13 23  7]]

     1   2   3
0
15   2  26  11
19  24  22  17
12  19  19   7
7   21  19  13
10   3  26   7
16  13  23   7

In [22]:
arr = np.random.randint(1 , 100 , size=(3 , 3))

df = pd.DataFrame(arr , index=['X' , 'Y' , 'Z'] , columns=['A' , 'B' , 'C'])
print(df)

print(df.loc['Y']['B'])

    A   B   C
X  54  45  30
Y  15  47  48
Z  41   9  51
47

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [25]:
df = pd.DataFrame(np.random.randint(1 , 16 , size=(5 , 3)) , columns=['A' , 'B' , 'C'])
df['D'] = df['A'] * df['B']
df

    A   B   C    D
0  14   2  13   28
1   2  15   2   30
2  13  11  12  143
3  12  11   4  132
4  12   6  14   72

In [ ]:
df = pd.DataFrame(np.random.randint(1 , 16 , size=(4 , 3)) , columns=['A' , 'B' , 'C'])

row_sum = df.sum(axis=1)
print(row_sum)

col_sum = df.sum(axis=0)
print(col_sum)

df

0    10
1    27
2    14
3    31
dtype: int64
A    25
B    29
C    28
dtype: int64

    A   B   C
0   1   1   8
1  11  12   4
2   8   3   3
3   5  13  13

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [41]:
df = pd.DataFrame(np.random.randint(1 , 16 , size=(5 , 3)) , columns=['A' , 'B' , 'C'])
df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print(df)

df.fillna(df.mean() , inplace=True)
df

      A     B     C
0  12.0   NaN  14.0
1   4.0  11.0   6.0
2   7.0  12.0   NaN
3   3.0   8.0  13.0
4   NaN   5.0   8.0

      A     B      C
0  12.0   9.0  14.00
1   4.0  11.0   6.00
2   7.0  12.0  10.25
3   3.0   8.0  13.00
4   6.5   5.0   8.00

In [44]:
df = pd.DataFrame(np.random.randint(1 , 16 , size=(6 , 3)) , columns=['A' , 'B' , 'C'])
df.iloc[0, 1] = np.nan
df.iloc[2, 2] = np.nan
df.iloc[4, 0] = np.nan
print(df)

df.dropna(inplace=True)
df

      A     B     C
0  13.0   NaN  14.0
1   6.0   2.0   6.0
2   7.0   4.0   NaN
3   8.0   3.0   1.0
4   NaN   8.0  11.0
5   9.0  10.0   5.0

     A     B    C
1  6.0   2.0  6.0
3  8.0   3.0  1.0
5  9.0  10.0  5.0

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [49]:
df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Value': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
print(df)

sum = df.groupby('Category')['Value'].sum()
print(sum)

mean = df.groupby('Category')['Value'].mean()
print(mean)

Original DataFrame:
  Category  Value
0        C     45
1        A     79
2        B     90
3        C     39
4        A     93
5        A     92
6        C     90
7        B     54
8        B     61
9        B     85
Category
A    264
B    290
C    174
Name: Value, dtype: int32
Category
A    88.0
B    72.5
C    58.0
Name: Value, dtype: float64

In [53]:
df = pd.DataFrame({'Product' : np.random.choice(['A' , 'B' , 'C'] , size=10) , 'Category': np.random.choice(['X' , 'Y' , 'Z'] , size=10) , 'Sales': np.random.randint(1 , 1000 , size=10)})
print(df)

sale = df.groupby('Category')['Sales'].sum()
sale

  Product Category  Sales
0       A        X    575
1       A        Y    914
2       A        X    659
3       B        Z    261
4       C        Y    680
5       A        X     16
6       A        Y    626
7       C        X    952
8       C        X    389
9       C        X    870

Category
X    3461
Y    2220
Z     261
Name: Sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [59]:
df1 = pd.DataFrame({'A' : np.random.randint(1 , 100 , size=10) , 'B' : np.random.randint(1 , 100 , size=10)})
df2 = pd.DataFrame({'B' : np.random.randint(1 , 100 , size=10) , 'C' : np.random.randint(1 , 100 , size=10)})
print(df1)
print(df2)

df = df1.merge(df2 , on='B')
df

    A   B
0  95  71
1  94  60
2   9  19
3  75  12
4  18  91
5  67  50
6  99  57
7  46  31
8   5  97
9   1  88
    B   C
0   7  76
1  65  86
2  14  61
3  88  75
4  64  82
5  12  30
6  91  70
7  76  88
8  53  68
9  80  12

    A   B   C
0  75  12  30
1  18  91  70
2   1  88  75

In [63]:
df1 = pd.DataFrame({'A' : np.random.randint(1 , 100 , size=3) , 'B' : np.random.randint(1 , 100 , size=3)})
df2 = pd.DataFrame({'C' : np.random.randint(1 , 100 , size=3) , 'D' : np.random.randint(1 , 100 , size=3)})
print(df1)
print(df2)

# Concatenate the DataFrames along the rows
concat_rows = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame (rows):")
print(concat_rows)

# Concatenate the DataFrames along the columns
concat_columns = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (columns):")
print(concat_columns)

    A   B
0  35  64
1  16  17
2  78  34
    C   D
0  33  97
1  62  76
2  15  17
Concatenated DataFrame (rows):
      A     B     C     D
0  35.0  64.0   NaN   NaN
1  16.0  17.0   NaN   NaN
2  78.0  34.0   NaN   NaN
0   NaN   NaN  33.0  97.0
1   NaN   NaN  62.0  76.0
2   NaN   NaN  15.0  17.0
Concatenated DataFrame (columns):
    A   B   C   D
0  35  64  33  97
1  16  17  62  76
2  78  34  15  17